apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yomi-argocd
  namespace: argocd
spec:
  project: default
<<<<<<< HEAD

=======
>>>>>>> 9f35768080c96e19a86df7ed215ba12bca33c1f3
  source:
    repoURL: https://github.com/YomiPounds/argo-yom.git
    targetRevision: HEAD
    path: dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true

