apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo23
  namespace: argocd
spec:
  project: ariyos

  source:
    repoURL: git@github.com:YomiPounds/argo-yom.git
    targetRevision: main
    path: /dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: myapp-argo

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true

